Dev test
whitequark/ipaddr.js pull request #177
Opened 2024-04-04 20:01 UTC by msimerson

- test: switch runner from mocha to node builtin
- test: remove useless done
  - they are only required for callback style async tests
- pkg: rm .travis.yml
- ci: update test runners
- ci: automatically test node LTS versions
- ci: update lint workflow

2024-04-08 13:43 UTC, whitequark requested changes
Thanks for picking this up!

2024-04-08 13:43 UTC, whitequark commented on package.json
> +    "lint": "npx eslint@^8 lib test",
I think I'd actually prefer having eslint pinned to `^8` in `devDependencies`?

2024-04-08 13:43 UTC, whitequark commented on package.json
> +    "test": "npx mocha@^10"
Happy to require node>=18 for development and ditch mocha, though.

2024-04-08 15:42 UTC, msimerson commented
Okay, so several changes here:

- dep(eslint): declared dependency on v8
- move the test file into lib (next to the code it runs). Naming files with `*.test.js` and putting them next to the files they test is apparently a pattern. Your thoughts?
- mocha -> `node --test`
  - ci: drop testing for older nodes that lack support for `node --test`

2024-04-08 15:59 UTC, msimerson commented
> naming files with *.test.js and putting them next to the files they test is apparently a pattern.

Something I just thought of and don't like, is that putting the test file in lib publishes it on npm. That's a small deal, but with 36m weekly downloads, the smallness has a very large multiplier. I've talked myself out of it. 😲 Sorry for the noise.

2024-04-09 13:51 UTC, merged

2024-04-09 13:51 UTC, whitequark commented
Thanks!